name: Deploy to VDS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VDS via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VDS_HOST || '81.200.157.102' }}
        username: ${{ secrets.VDS_USER || 'root' }}
        key: ${{ secrets.VDS_SSH_KEY }}
        port: ${{ secrets.VDS_PORT || 22 }}
        script: |
          # Navigate to project directory
          cd /opt/trenergram

          # Clean any local changes to avoid conflicts
          git reset --hard
          git clean -fd

          # Pull latest changes
          git pull origin main

          # Rebuild and restart Docker containers
          docker-compose down
          docker-compose build --no-cache backend bot
          docker-compose up -d

          # Deploy webapp files
          if [ -d "webapp" ]; then
            # Deploy webapp files
            rm -rf /var/www/trenergram/*
            cp -r webapp/* /var/www/trenergram/
          fi

          # Update nginx config if exists
          if [ -f "nginx-ssl.conf" ]; then
            cp nginx-ssl.conf /etc/nginx/sites-available/trenergram
            nginx -t && nginx -s reload
          fi

          # Apply database migrations
          docker-compose exec -T backend python apply_migrations.py || echo "Migrations applied or not needed"

          # Check container status
          docker-compose ps

          echo "✅ Deployment completed successfully!"