name: Deploy to VDS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VDS via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VDS_HOST || '81.200.157.102' }}
        username: ${{ secrets.VDS_USER || 'root' }}
        key: ${{ secrets.VDS_SSH_KEY }}
        port: ${{ secrets.VDS_PORT || 22 }}
        script: |
          # Navigate to project directory
          cd /opt/trenergram

          # Pull latest changes
          git pull origin main

          # Build and restart backend
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d

          # Build frontend for mini-app (if exists)
          if [ -d "frontend" ]; then
            cd frontend
            npm install
            npm run build
            # Copy built files to nginx directory for /app path
            sudo mkdir -p /var/www/trenergram/
            sudo cp -r dist/* /var/www/trenergram/

            # Update nginx configuration if needed
            # Check if SSL is installed
            if [ -f /etc/letsencrypt/live/trenergram.ru/fullchain.pem ]; then
              # Use SSL config if certificate exists
              if [ -f /opt/trenergram/nginx-ssl.conf ]; then
                sudo cp /opt/trenergram/nginx-ssl.conf /etc/nginx/sites-available/trenergram
              fi
            else
              # Use non-SSL config
              sudo cp /opt/trenergram/nginx-config.conf /etc/nginx/sites-available/trenergram
            fi
            sudo nginx -t && sudo systemctl reload nginx
          fi

          echo "✅ Deployment completed at $(date)"

    - name: Check deployment
      run: |
        sleep 10
        response=$(curl -s -o /dev/null -w "%{http_code}" https://trenergram.ru/health)
        if [ $response -eq 200 ]; then
          echo "✅ Deployment successful - API is responding"
        else
          echo "⚠️ API returned status code: $response"
        fi